apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}

    spec:
      imagePullSecrets:
        - name: harbor-credentials

      containers:
        - name: {{ .Chart.Name }}
          image: registry.hibbard.dev/proxy/pihole/pihole:2023.05.2
          imagePullPolicy: IfNotPresent

          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: time-zone

            - name: PIHOLE_DNS_
              valueFrom:
                configMapKeyRef:
                  name: pihole-config
                  key: dns-servers

            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-admin
                  key: password

            - name: TEMPERATUREUNIT
              value: f

          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/index.php
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5

          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP

          volumeMounts:
            - name: etc
              mountPath: /etc/pihole
            - name: adlist
              mountPath: /etc/pihole/adlists.list
              subPath: adlists.list

          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 500m
              
      volumes:
        - name: etc
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}
        - name: adlist
          configMap:
            name: pihole-config
            items: 
              - key: adlist
                path: adlists.list
