apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: {{ .Chart.Name }}
    allow-harbor-credentials: "true" 
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{  .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  
spec:
  rules:
    - host: {{ .Values.ingressDns }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}-web
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.ingressDns }}
      secretName: {{ .Values.ingressTlsSecret }}

