apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    allow-hibbard-wildcard-tls: 'true'
    allow-harbor-credentials: "true" 
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{  .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}