apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pihole-admin
  namespace:  {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  encryptedData:
    password: AgCX/sRltdryzfyymsOs/aV5JdiOfX3F9ggX4Knj6mwDBdrK56xB1regRtymHCr2vAoej+6L50JLSV4F6tiw7usTPSg49oNMrdRdOtxhUj+aMj0vBjfbMI1ZKGGeQx3Xfkr84DkVP3gGqZchmqpwZIbu4d9f3rFSKIF2G6jlTta2CwRsH19Y1UBuhoxwZFdlMHgNolF/Ak5vwcejnGwlSrBnRgA1urKlbbnCTh2srkJV+s8v3XYeLfGFbQsFzZX3zA6GDc7M4H0oabdEWBJEsGmVeG7UfSQ/yfLO3uAqIuiVJU6XpuuLx/Dy9ytHAfwaCwMjjgAPIFduu5OXhxmxGAUg6qLW0IdoTAF8kouDp3MNw7y6fBdyv/PP305wL1ieauTjh/TUwujnXpL8+zNYQ6WsDWNDH0k3hmaqd0CRwpprOObJ0auIv8BuuPrZ2k1V5ab1ly38OUd5cADzYwLtBe7zjK81MteLaE3M9BgrxQUEn1APOub0L65d2YAtvEV7FDM+Icu/swmah2lWpFriMfkP4YPM4vfLgZEuX3+Tbf3ai63moH44XGs7Ni+HH8BqWRN+wPgWzUrWttuYegg6za8m0JAVSnEbmtWIE2Rhu7Faq+M+N/MQ/m4pE+MJ/JWzS5pIwzJn5W8rWWCRk8CrVwBp5PvgJ2oDB8fjJDhl9tHYFWJ40lZkuUhrHPtsCcR8+Ei2hA/9OXjG+A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pihole-admin
    type: Opaque
