apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-web
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

spec:
  selector:
    app: {{ .Chart.Name }}

  ports:
  - port: 80
    targetPort: 80
    name: http

  - port: 443
    targetPort: 443
    name: https