apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-dns
  namespace: {{ .Values.namespace }}
  annotations:
    metallb.universe.tf/address-pool: pihole-pool
    metallb.universe.tf/allow-shared-ip: dns
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: LoadBalancer